{
 "title": "Pragma Monitoring - Starknet",
 "tags": [
  "pragma",
  "monitoring",
  "starknet"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki", "query": "loki" },
   {
    "name": "network",
    "query": {
     "query": "label_values(pragma_pair_price,network)"
    }
   },
   {
    "name": "pair",
    "query": {
     "query": "label_values(pragma_pair_price{network=\"$network\"},pair)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Publishers Balance (STRK)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "pragma_publisher_balance_strk{network=\"$network\"}",
     "legendFormat": "{{publisher}}"
    }
   ]
  },
  {
   "title": "Number of Sources",
   "type": "bargauge",
   "gridPos": { "h": 28, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pragma_pair_num_sources{network=\"$network\", type=\"spot\"}",
     "legendFormat": "{{pair}}"
    }
   ]
  },
  {
   "title": "Deviation by Source vs Onchain Median",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pragma_deviation_vs_median{network=\"$network\", pair=\"$pair\", type=\"spot\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Deviation by Source vs DefiLlama",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pragma_deviation_vs_defillama{network=\"$network\", pair=\"$pair\", type=\"spot\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Time Since Last Update (Publisher)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pragma_publisher_last_update_seconds{network=\"$network\", type=\"spot\"}",
     "legendFormat": "{{publisher}}"
    }
   ]
  },
  {
   "title": "Pair Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "pragma_pair_price{network=\"$network\", pair=\"$pair\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"pragma-monitoring-logs-service\"} | json | line_format \"{{.body}}\""
    }
   ]
  },
  {
   "title": "Time Since Last Update (Pair)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pragma_pair_last_update_seconds{network=\"$network\"}",
     "legendFormat": "{{pair}}"
    }
   ]
  },
  {
   "title": "Deviation Onchain vs DefiLlama",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pragma_deviation_onchain_vs_offchain{network=\"$network\", type=\"spot\"}",
     "legendFormat": "{{pair}}"
    }
   ]
  },
  {
   "title": "Latest Indexed Block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pragma_indexer_latest_block{network=\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexed Events Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "targets": [
    {
     "expr": "pragma_indexer_events_count{network=\"$network\"}",
     "legendFormat": "{{pair}} - {{event_type}}"
    }
   ]
  }
 ]
}