apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.gcpSecrets.externalSecret.name }}
  namespace: monitoring
spec:
  refreshInterval: {{ .Values.gcpSecrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.gcpSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.envFromSecret.secretName }}
  data:
    - secretKey: .env
      remoteRef:
        key: {{ .Values.gcpSecrets.externalSecret.secretPath }}
        version: latest
