groups:
  - name: Oracle
    rules:
      - alert: TimeSinceLastUpdateTooHigh
        expr: time_since_last_update_seconds > 1800
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Time since the last update is too high"
          description: "The time since the last update from {{ $labels.publisher }} has exceeded 1800 seconds."

      - alert: WrongPrice
        expr: abs(price_deviation) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Price deviation is too high"
          description: "The price deviation of {{ $labels.pair }} from {{ $labels.source }} has deviated for more than 5% with the reference price from DefiLlama."

      - alert: TooFewSources
        expr: num_sources < 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Too few sources"
          description: "The number of sources for {{ $labels.pair }} has fallen below 5."

      - alert: SourceDeviation
        expr: abs(price_deviation_source) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Source deviation is too high"
          description: "The source deviation of {{ $labels.pair }} from {{ $labels.source }} has deviated for more than 5% with the Oracle median price."

      - alert: IndexerDown
        expr: indexer_blocks_left > 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Indexer is down"
          description: "The {{ $labels.network }} indexer for {{ $labels.type }} is lagging behind 10 blocks."

      - alert: PublisherBalanceLow
        expr: publisher_balance < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Publisher balance is low"
          description: "The {{ $labels.publisher }} balance is below 0.1 ETH."

      - alert: PriceDeviationTooHigh
        expr: abs(on_off_price_deviation) > 0.025
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Price deviation is too high"
          description: "The median on-chain price of {{ $labels.pair }} has deviated for more than 2.5% with the reference price from DefiLlama."

  - name: API
    rules:
      - alert: TimeSinceLastUpdateTooHigh
        expr: api_time_since_last_update > 1800
        for: 5m
        labels:
          severity: warning
          group: API
        annotations:
          summary: "Time since the last update is too high"
          description: "The time since the last update for {{ $labels.pair }} has exceeded 1800 seconds."

      - alert: WrongPrice
        expr: abs(api_price_deviation) > 0.025
        for: 5m
        labels:
          severity: warning
          group: API
        annotations:
          summary: "Price deviation is too high"
          description: "The median price of {{ $labels.pair }} from our API has deviated for more than 2.5% with the reference price from DefiLlama."

      - alert: TooFewSources
        expr: api_num_sources < 1
        for: 5m
        labels:
          severity: critical
          group: API
        annotations:
          summary: "Too few sources"
          description: "The number of sources for {{ $labels.pair }} has fallen below 1."

      - alert: SequencerDeviation
        expr: abs(api_sequencer_deviation) > 0.02
        for: 5m
        labels:
          severity: critical
          group: API
        annotations:
          summary: "Sequencer deviation is too high"
          description: "The ETH/STRK price has deviated by more than 2% from the sequencer price."

  - name: VRF
    rules:
      - alert: TimeInPendingStatusTooLong
        expr: vrf_time_since_oldest_request_in_pending_status > 900 # 900 Seconds = 15 minutes
        for: 5m
        labels:
          severity: critical
          group: VRF
        annotations:
          summary: "VRF request has been in pending status for too long"
          description: 'The oldest VRF request for network "{{ $labels.network }}" has been in the pending status for more than 15 minutes.'
