global:
  resolve_timeout: 5m

route:
  group_by: ["instance", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "main-telegram"

receivers:
  - name: "main-telegram"
    telegram_configs:
      - bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: '-1001904637278'

