global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus_monitoring"
    static_configs:
      - targets: ["host.docker.internal:8081"]

rule_files:
  - "alerts.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - host.docker.internal:9093
