global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus_monitoring'
    static_configs:
      - targets: ['127.0.0.1:8080']
rule_files:
  - "alerts.rules.yml"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
