replicaCount: 1

image:
  repository: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pragma-monitoring
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: false

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: ""
  prometheus.io/path: "/metrics"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  Nodelabel: "node-devnet"

tolerations:
  - key: "devnet"
    operator: "Equal"
    value: "reserved"
    effect: "NoSchedule"

affinity: {}

ingress:
  enabled: true
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  ingressClassName: nginx-internal
  hosts:
    - host: monitoring.devnet.pragma.build
      paths: ["/"]
  tls: []

# GCP Secrets Configuration
gcpSecrets:
  enabled: true
  projectId: ${PROJECT_ID}
  secretStore:
    name: "monitoring-secrets-store"
  externalSecret:
    name: "monitoring-secrets"
    secretPath: "projects/{PROJECT_ID_APP}/secrets/monitoring-secrets"
    refreshInterval: "1h"

# Environment variables from secret
envFromSecret:
  secretName: "monitoring-env-secrets"
