replicaCount: 1

image:
  repository: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/pragma-monitoring
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: false

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: ""
  prometheus.io/path: "/metrics"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: 2000m    # Increased from 1000m
    memory: 2Gi   # Increased from 1Gi
  requests:
    cpu: 1000m    # Increased from 500m
    memory: 1Gi   # Increased from 512Mi

nodeSelector:
  Nodelabel: "node-devnet"

tolerations:
  - key: "devnet"
    operator: "Equal"
    value: "reserved"
    effect: "NoSchedule"

affinity: {}

ingress:
  enabled: true
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  ingressClassName: nginx-internal
  hosts:
    - host: monitoring.devnet.pragma.build
      paths: ["/"]
  tls: []

# GCP Secrets Configuration
gcpSecrets:
  enabled: true
  projectId: ${PROJECT_ID}
  secretStore:
    name: "monitoring-secrets-store"
    auth:
      workloadIdentity:
        clusterLocation: ${_REGION}
        clusterName: ${_CLUSTER_NAME}
  externalSecret:
    name: "monitoring-secrets"
    secretPath: "monitoring-secrets"
    refreshInterval: "1h"

# Environment variables from secret
envFromSecret:
  secretName: "monitoring-env-secrets"

env:
  - name: RUST_BACKTRACE
    value: "1"
  - name: COINGECKO_RETRY_DELAY
    value: "5000"
  - name: COINGECKO_MAX_RETRIES
    value: "3"
